import os

from flask import Flask, render_template, request, send_from_directory
from config import Config

from database.database import db
from database.models import Issue

from services.dashboard_service import get_dashboard_stats
from services.issue_service import save_issue

from routes.report_routes import bp as report_bp
from routes.tracking_routes import bp as tracking_bp
from routes.authority_routes import bp as authority_bp
from routes.dashboard_routes import bp as dashboard_bp
from routes.assistant_routes import bp as assistant_bp


app = Flask(__name__)

app.config.from_object(Config)

db.init_app(app)


# ----------------------------
# Register Blueprints
# ----------------------------

app.register_blueprint(report_bp)
app.register_blueprint(tracking_bp)
app.register_blueprint(authority_bp)
app.register_blueprint(dashboard_bp)
app.register_blueprint(assistant_bp)


# ----------------------------
# Create folders & database
# ----------------------------

with app.app_context():

    os.makedirs("instance", exist_ok=True)
    os.makedirs("uploads/issues", exist_ok=True)
    os.makedirs("uploads/temp", exist_ok=True)

    db.create_all()


# ----------------------------
# Home
# ----------------------------

@app.route("/")
def home():

    stats = get_dashboard_stats()

    return render_template(
        "index.html",
        stats=stats
    )


# ----------------------------
# Citizen Report Page
# ----------------------------

@app.route("/report")
def report():

    return render_template("citizen/report.html")


# ----------------------------
# Submit Report
# ----------------------------

@app.route("/submit-report", methods=["POST"])
def submit_report():

    image = request.files["image"]

    title = request.form["title"]

    description = request.form["description"]

    category = request.form["category"]

    address = request.form["address"]

    latitude = request.form.get("latitude")

    longitude = request.form.get("longitude")

    contact = request.form.get("contact", "")

    anonymous = "anonymous" in request.form

    # Validation
    if not latitude or not longitude:
        return "Please select a location on the map before submitting."

    result = save_issue(

        image=image,

        title=title,

        description=description,

        category=category,

        address=address,

        latitude=latitude,

        longitude=longitude,

        contact=contact,

        anonymous=anonymous

    )

    return render_template(
        "citizen/analysis.html",
        result=result
    )
@app.route("/uploads/<path:filename>")
def uploaded_file(filename):
    return send_from_directory("uploads", filename)

@app.route("/issue/<tracking_id>")
def issue_details(tracking_id):

    issue = Issue.query.filter_by(
        tracking_id=tracking_id
    ).first()

    if issue is None:
        return "Issue not found"

    result = {

        "issue": issue,

        "scout": {

            "issue_type": issue.issue_type,

            "severity": issue.severity,

            "confidence": issue.confidence,

            "description": issue.ai_summary

        },

        "risk": {

            "risk_level": issue.risk_level,

            "risk_score": issue.risk_score,

            "reason": "Generated by Risk AI"

        },

        "authority": {

            "authority": issue.authority,

            "department": issue.department,

            "priority": issue.priority

        },

        "resolution": {

            "steps": [

                "Issue Registered",

                "Assigned to Department",

                "Resolution In Progress"

            ],

            "estimated_time": issue.estimated_time,

            "resources": issue.resources

        }

    }

    return render_template(

        "citizen/analysis.html",

        result=result

    )
# ----------------------------
# Run Server
# ----------------------------

if __name__ == "__main__":
    app.run(debug=True)
